version: "2.4"

services:
  server:
    build:
      dockerfile: Dockerfile
      context: .
      target: server-dev
    ports:
      - "5000:5000"
    volumes:
      - .:/app:delegated
    env_file:
      - .env
